apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-microservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-microservice
  template:
    metadata:
      labels:
        app: sample-microservice
    spec:
      containers:
      - name: sample-microservice
        image: sample-microservice:latest
        ports:
        - containerPort: 5000
