apiVersion: v1
kind: Service
metadata:
  name: sample-microservice-service
spec:
  selector:
    app: sample-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
