apiVersion: v1
kind: Service
metadata:
  name: unique-number-generator-service
spec:
  selector:
    app: unique-number-generator-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
